[accounts.drexel]
default = true
email = "ss5278@drexel.edu"
display-name = "ss5278"
downloads-dir = "/Users/satwikshresth/Email"

backend.type = "imap"
backend.host = "outlook.office365.com"
backend.port = 993
backend.login = "ss5278@drexel.edu"
backend.encryption.type = "tls"
backend.auth.type = "password"
backend.auth.command = "gopass show -o email/ss5278@drexel.edu"

message.send.backend.type = "smtp"
message.send.backend.host = "smtp.office365.com"
message.send.backend.port = 587
message.send.backend.login = "ss5278@drexel.edu"
message.send.backend.encryption.type = "start-tls"
message.send.backend.auth.type = "password"
message.send.backend.auth.command = "gopass show -o drexel"

